name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-build-deploy:
    name: Test, Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Restore Cache ♻
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup 🔧
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.0
          run_install: true

      - name: Check 🔎
        run: pnpm run check

      - name: Test ✅
        run: pnpm run test

      - name: Build 🏗
        run: pnpm run build

      - name: CNAME 🧾
        run: echo zacktype.jonasgeiler.com > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: dist
