name: Test, Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  text-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Restore Cache ♻
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup 🔧
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.0
          run_install: true

      - name: Check 🔎
        run: pnpm run check

      - name: Test ✅
        run: pnpm run test

      - name: Build 🏗
        run: pnpm run build

      - run: echo zacktype.skayo.dev > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          git-config-name: SkayoBot
          git-config-email: frederike.gnampf@gmail.com
          clean: true
